import json, sys, os

data = json.load(sys.stdin)
masters = data["master_nodes"]["value"]
workers = data["worker_nodes"]["value"]
primary_ip = data["primary_master_ip"]["value"]

ini = "# Auto-generated by gen_inventory.py — do not edit\n\n"
ini += "[masters]\n"
for k, v in sorted(masters.items()):
    ini += f"{v['hostname']}  ansible_host={v['ip']}  ansible_user=root\n"

ini += "\n[workers]\n"
for k, v in sorted(workers.items()):
    ini += f"{v['hostname']}  ansible_host={v['ip']}  ansible_user=root\n"

ini += "\n[k8s_cluster:children]\nmasters\nworkers\n"
ini += f"\n[k8s_cluster:vars]\nansible_ssh_common_args='-o StrictHostKeyChecking=no'\nprimary_master_ip={primary_ip}\n"

os.makedirs("inventory", exist_ok=True)
with open("inventory/hosts.ini", "w") as f:
    f.write(ini)

print(ini)
print("✅ inventory/hosts.ini written")
