#!/usr/bin/env python3
"""
gen_inventory.py — Generate Ansible inventory from Terraform JSON output.

Usage (from ansible/ directory):
  terraform -chdir=../terraform output -json | python3 scripts/gen_inventory.py

Writes:  ansible/inventory/hosts.ini
         ansible/inventory/hosts.yml  (YAML form for reference)
"""

import json
import sys
import os

def main():
    raw = sys.stdin.read()
    tf = json.loads(raw)

    masters = tf.get("master_nodes", {}).get("value", {})
    workers = tf.get("worker_nodes", {}).get("value", {})
    primary_master_ip = tf.get("primary_master_ip", {}).get("value", "")

    # ── INI inventory ──────────────────────────────────────────
    lines = [
        "# Auto-generated by gen_inventory.py — do not edit by hand",
        "",
        "[masters]",
    ]
    for name, info in sorted(masters.items()):
        lines.append(
            f"{info['hostname']}  ansible_host={info['ip']}  ansible_user=root"
        )

    lines += ["", "[workers]"]
    for name, info in sorted(workers.items()):
        lines.append(
            f"{info['hostname']}  ansible_host={info['ip']}  ansible_user=root"
        )

    lines += [
        "",
        "[k8s_cluster:children]",
        "masters",
        "workers",
        "",
        "[k8s_cluster:vars]",
        "ansible_ssh_common_args='-o StrictHostKeyChecking=no'",
        f"primary_master_ip={primary_master_ip}",
    ]

    ini_path = os.path.join(os.path.dirname(__file__), "..", "inventory", "hosts.ini")
    ini_path = os.path.normpath(ini_path)
    os.makedirs(os.path.dirname(ini_path), exist_ok=True)

    with open(ini_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"[gen_inventory] Written: {ini_path}")

    # ── YAML inventory (optional, for readability) ─────────────
    yml_lines = [
        "# Auto-generated by gen_inventory.py",
        "all:",
        "  children:",
        "    k8s_cluster:",
        "      children:",
        "        masters:",
        "          hosts:",
    ]
    for name, info in sorted(masters.items()):
        yml_lines += [
            f"            {info['hostname']}:",
            f"              ansible_host: {info['ip']}",
            f"              ansible_user: root",
        ]
    yml_lines += ["        workers:", "          hosts:"]
    for name, info in sorted(workers.items()):
        yml_lines += [
            f"            {info['hostname']}:",
            f"              ansible_host: {info['ip']}",
            f"              ansible_user: root",
        ]
    yml_lines += [
        "      vars:",
        "        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'",
        f"        primary_master_ip: {primary_master_ip}",
    ]

    yml_path = os.path.join(os.path.dirname(__file__), "..", "inventory", "hosts.yml")
    yml_path = os.path.normpath(yml_path)
    with open(yml_path, "w") as f:
        f.write("\n".join(yml_lines) + "\n")

    print(f"[gen_inventory] Written: {yml_path}")

if __name__ == "__main__":
    main()
